apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  DB_HOST: mysql-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysbackendql
  namespace: expense
  labels:
    app: backend
    tier: app
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend-cont
        image: joindevops/backend:v1
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: expense
  name: backend-svc
spec:
  selector:
    app: backend
    tier: app
    project: expense
  ports:
  - name: backend-port
    port: 8080
    targetPort: 8080

